version: '3'
services:
  app:
    build: .
    container_name: front_app1
    volumes:
      - .:/opt
    ports:
      - "8080:8800"
    depends_on:
      - mongodb
    tty: true    
  mongodb:
    image: mongo:3.2.17-jessie
    container_name: likith_mongodb_
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: chown -R $(whoami):staff /data
    command: mongod --logpath=/dev/null
  



